FROM jenkinsci/blueocean:latest
# FROM jenkins:alpine

# -----------------------
# 起動オプション
# docker build -t try_ci_jenkins -f Dockerfile-jenkins .
# 
# ビルドコマンド
# docker run -p 8080:8080 -v "/e/docker/try-ci/jenkins/.ivy2:/root/.ivy2" --name try_ci_jenkins try_ci_jenkins 
# docker run -p 8080:8080 -v "/e/docker/try-ci/jenkins/.ivy2:/var/jenkins_home" --name try_ci_jenkins try_ci_jenkins 
#

USER root

RUN apk add --no-cache \
		ca-certificates \
		curl \
		openssl

ENV DOCKER_BUCKET test.docker.com
ENV DOCKER_VERSION 17.05.0-ce-rc1
ENV DOCKER_SHA256 4561742c2174c01ffd0679621b66d29f8a504240d79aa714f6c58348979d02c6

RUN set -x \
	&& curl -fSL "https://${DOCKER_BUCKET}/builds/Linux/x86_64/docker-${DOCKER_VERSION}.tgz" -o docker.tgz \
	&& echo "${DOCKER_SHA256} *docker.tgz" | sha256sum -c - \
	&& tar -xzvf docker.tgz \
	&& mv docker/* /usr/local/bin/ \
	&& rmdir docker \
	&& rm docker.tgz \
	&& docker -v

COPY docker-entrypoint.sh /usr/local/bin/

#RUN install-plugins.sh antisamy-markup-formatter matrix-auth pipeline-model-definition blueocean:$BLUEOCEAN_VERSION \
#  docker-plugin sbt

RUN install-plugins.sh docker-plugin sbt

COPY sbt-0.13.15.zip /tmp
RUN cd /tmp && unzip sbt-0.13.13.zip && mv /tmp/sbt /usr/local #&& \
# ln -s /usr/local/sbt-launcher-packaging-0.13.13 /usr/local/sbt  

RUN curl -L "https://github.com/docker/compose/releases/download/1.11.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
 chmod +x /usr/local/bin/docker-compose

#USER jenkins
USER root

