# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
AdminUser.create(:email => "admin@test.com", :password => "hogehoge", :password_confirmation => "hogehoge")
P2Simple.create(:name => "やの", :age=>32 , :memo => "ばかぼんど")
P2Simple.create(:name => "やの", :age=>32 , :memo => "ばかぼんど")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
P2Simple.create(:name => "たごさく", :age=>32 , :memo => "すわっと")
ｖ